apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  selector:
    app: auth
  type: ClusterIP # not be reacheable from the outside
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80